<?php 
return array(
	'index'=>array(
		'title'=>'首页',
		'url'=>'/admin/index'
	),
	'banner'=>array(
		'title'=>'轮播图',
		'url'=>'/admin/banner'
	),
	'banner_space'=>array(
		'title'=>'轮播图位置',
		'url'=>'/admin/banner_space'
	),
	'product'=>array(
		'title'=>'产品',
		'url'=>'/admin/product'
	),
	'product_class'=>array(
		'title'=>'产品分类',
		'url'=>'/admin/product_class'
	),
	'news'=>array(
		'title'=>'资讯',
		'url'=>'/admin/news'
	),
	'news_class'=>array(
		'title'=>'资讯分类',
		'url'=>'/admin/news_class'
	),
	'advert'=>array(
		'title'=>'广告',
		'url'=>'/admin/advert'
	),
	'advert_space'=>array(
		'title'=>'广告位',
		'url'=>'/admin/advert_space'
	),
	'pages'=>array(
		'title'=>'单页',
		'url'=>'/admin/pages'
	),
	'member'=>array(
		'title'=>'会员',
		'url'=>'/admin/member'
	),
	'account'=>array(
		'title'=>'管理员',
		'url'=>'/admin/account'
	),
	'account_group'=>array(
		'title'=>'用户组',
		'url'=>'/admin/account_group'
	),
	'setting'=>array(
		'title'=>'网站设置',
		'url'=>'/admin/setting'
	),
	'links'=>array(
		'title'=>'友情链接',
		'url'=>'/admin/links'
	),
	'logs'=>array(
		'title'=>'日志',
		'url'=>'/admin/logs'
	)
);
 ?>